### ISSUE TITLE
OverflowError: cannot serialize a bytes object larger than 4 GiB

### ISSUE THREAD

**Issue by karin0018** [FadedCosine/kNN-KD#2]
I try to achieve your results on WMT19 law domain dataset, but when I run `train_knnmt.sh`, I met the Overflow error：
```
2022-07-25 06:32:40 2022-07-25 06:32:39 | INFO | fairseq.utils | ***********************CUDA enviroments for all 4 workers***********************
2022-07-25 06:32:40 2022-07-25 06:32:39 | INFO | fairseq.utils | rank   0: capabilities =  7.0  ; total memory = 31.749 GB ; name = Tesla V100-PCIE-32GB                    
2022-07-25 06:32:40 2022-07-25 06:32:39 | INFO | fairseq.utils | rank   1: capabilities =  7.0  ; total memory = 31.749 GB ; name = Tesla V100-PCIE-32GB                    
2022-07-25 06:32:40 2022-07-25 06:32:39 | INFO | fairseq.utils | rank   2: capabilities =  7.0  ; total memory = 31.749 GB ; name = Tesla V100-PCIE-32GB                    
2022-07-25 06:32:40 2022-07-25 06:32:39 | INFO | fairseq.utils | rank   3: capabilities =  7.0  ; total memory = 31.749 GB ; name = Tesla V100-PCIE-32GB                    
2022-07-25 06:32:40 2022-07-25 06:32:39 | INFO | fairseq.utils | ***********************CUDA enviroments for all 4 workers***********************
2022-07-25 06:32:40 2022-07-25 06:32:39 | INFO | fairseq_cli.train | training on 4 devices (GPUs/TPUs)
2022-07-25 06:32:40 2022-07-25 06:32:39 | INFO | fairseq_cli.train | max tokens per GPU = 1280 and max sentences per GPU = None
2022-07-25 06:32:40 2022-07-25 06:32:39 | INFO | fairseq.trainer | no existing checkpoint found /mnt/blob/v-ruilv/mt/checkpoints/wmt19_law/knn4_temp10_time_itp64/checkpoint_last.pt
2022-07-25 06:32:40 2022-07-25 06:32:39 | INFO | fairseq.trainer | loading train data for epoch 1
2022-07-25 06:32:40 2022-07-25 06:32:39 | INFO | fairseq.tasks.translation_with_stored_knnls | Keys are fp16 and vals are int
2022-07-25 06:32:46 2022-07-25 06:32:45 | INFO | fairseq.tasks.translation_with_stored_knnls | Loaded /mnt/blob/v-ruilv/mt/data-knntarget/wmt19_deen_kNN_KD-law/bs1_fp16_distances_train_k64.mmp
2022-07-25 06:32:55 2022-07-25 06:32:54 | INFO | fairseq.tasks.translation_with_stored_knnls | Loaded /mnt/blob/v-ruilv/mt/data-knntarget/wmt19_deen_kNN_KD-law/bs1_knntargets_train_k64.mmp
2022-07-25 06:32:55 2022-07-25 06:32:55 | INFO | fairseq.data.data_utils | loaded 467309 examples from: /mnt/blob/v-ruilv/mt/data-bin/wmt19-deen-multi-domain/law/train.de-en.de
2022-07-25 06:32:58 2022-07-25 06:32:56 | INFO | fairseq.data.data_utils | loaded 467309 examples from: /mnt/blob/v-ruilv/mt/data-bin/wmt19-deen-multi-domain/law/train.de-en.en
2022-07-25 06:32:58 2022-07-25 06:32:56 | INFO | fairseq.tasks.translation_with_stored_knnls | /mnt/blob/v-ruilv/mt/data-bin/wmt19-deen-multi-domain/law train de-en 467309 examples
2022-07-25 06:32:58 /opt/conda/lib/python3.7/site-packages/torch/nn/parallel/distributed.py:468: UserWarning: The `check_reduction` argument in `DistributedDataParallel` module is deprecated. Please avoid using it.
2022-07-25 06:32:58   "The `check_reduction` argument in `DistributedDataParallel` "
2022-07-25 06:32:58 /opt/conda/lib/python3.7/site-packages/torch/nn/parallel/distributed.py:468: UserWarning: The `check_reduction` argument in `DistributedDataParallel` module is deprecated. Please avoid using it.
2022-07-25 06:32:58   "The `check_reduction` argument in `DistributedDataParallel` "
2022-07-25 06:32:58 /opt/conda/lib/python3.7/site-packages/torch/nn/parallel/distributed.py:468: UserWarning: The `check_reduction` argument in `DistributedDataParallel` module is deprecated. Please avoid using it.
2022-07-25 06:32:58   "The `check_reduction` argument in `DistributedDataParallel` "
2022-07-25 06:32:58 /opt/conda/lib/python3.7/site-packages/torch/nn/parallel/distributed.py:468: UserWarning: The `check_reduction` argument in `DistributedDataParallel` module is deprecated. Please avoid using it.
2022-07-25 06:32:58   "The `check_reduction` argument in `DistributedDataParallel` "
2022-07-25 06:32:58 2022-07-25 06:32:57 | WARNING | fairseq.tasks.fairseq_task | 1 samples have invalid sizes and will be skipped, max_positions=(1024, 1024), first few sample ids=[386753]
2022-07-25 06:32:58 2022-07-25 06:32:57 | WARNING | fairseq.tasks.fairseq_task | 1 samples have invalid sizes and will be skipped, max_positions=(1024, 1024), first few sample ids=[386753]
2022-07-25 06:32:58 2022-07-25 06:32:57 | WARNING | fairseq.tasks.fairseq_task | 1 samples have invalid sizes and will be skipped, max_positions=(1024, 1024), first few sample ids=[386753]
2022-07-25 06:32:58 2022-07-25 06:32:57 | WARNING | fairseq.tasks.fairseq_task | 1 samples have invalid sizes and will be skipped, max_positions=(1024, 1024), first few sample ids=[386753]
2022-07-25 06:32:58 2022-07-25 06:32:57 | INFO | fairseq.trainer | begin training epoch 1
2022-07-25 06:33:10 Traceback (most recent call last):
2022-07-25 06:33:10   File "train.py", line 14, in <module>
2022-07-25 06:33:10     cli_main()
2022-07-25 06:33:10   File "/home/v-ruilv/kNN-KD/fairseq_cli/train.py", line 353, in cli_main
2022-07-25 06:33:10     distributed_utils.call_main(args, main)
2022-07-25 06:33:10   File "/home/v-ruilv/kNN-KD/fairseq/distributed_utils.py", line 286, in call_main
2022-07-25 06:33:10     nprocs=args.distributed_num_procs,
2022-07-25 06:33:10   File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
2022-07-25 06:33:10     return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
2022-07-25 06:33:10   File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
2022-07-25 06:33:10     while not context.join():
2022-07-25 06:33:10   File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 150, in join
2022-07-25 06:33:10     raise ProcessRaisedException(msg, error_index, failed_process.pid)
2022-07-25 06:33:10 torch.multiprocessing.spawn.ProcessRaisedException: 
2022-07-25 06:33:10 
2022-07-25 06:33:10 -- Process 2 terminated with the following error:
2022-07-25 06:33:10 Traceback (most recent call last):
2022-07-25 06:33:10   File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
2022-07-25 06:33:10     fn(i, *args)
2022-07-25 06:33:10   File "/home/v-ruilv/kNN-KD/fairseq/distributed_utils.py", line 270, in distributed_main
2022-07-25 06:33:10     main(args, **kwargs)
2022-07-25 06:33:10   File "/home/v-ruilv/kNN-KD/fairseq_cli/train.py", line 125, in main
2022-07-25 06:33:10     valid_losses, should_stop = train(args, trainer, task, epoch_itr)
2022-07-25 06:33:10   File "/opt/conda/lib/python3.7/contextlib.py", line 74, in inner
2022-07-25 06:33:10     return func(*args, **kwds)
2022-07-25 06:33:10   File "/home/v-ruilv/kNN-KD/fairseq_cli/train.py", line 204, in train
2022-07-25 06:33:10     for i, samples in enumerate(progress):
2022-07-25 06:33:10   File "/home/v-ruilv/kNN-KD/fairseq/logging/progress_bar.py", line 243, in __iter__
2022-07-25 06:33:10     for i, obj in enumerate(self.iterable, start=self.n):
2022-07-25 06:33:10   File "/home/v-ruilv/kNN-KD/fairseq/data/iterators.py", line 59, in __iter__
2022-07-25 06:33:10     for x in self.iterable:
2022-07-25 06:33:10   File "/home/v-ruilv/kNN-KD/fairseq/data/iterators.py", line 469, in _chunk_iterator
2022-07-25 06:33:10     for x in itr:
2022-07-25 06:33:10   File "/home/v-ruilv/kNN-KD/fairseq/data/iterators.py", line 59, in __iter__
2022-07-25 06:33:10     for x in self.iterable:
2022-07-25 06:33:10   File "/home/v-ruilv/kNN-KD/fairseq/data/iterators.py", line 591, in __next__
2022-07-25 06:33:10     raise item
2022-07-25 06:33:10   File "/home/v-ruilv/kNN-KD/fairseq/data/iterators.py", line 522, in run
2022-07-25 06:33:10     for item in self._source:
2022-07-25 06:33:10   File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
2022-07-25 06:33:10     return self._get_iterator()
2022-07-25 06:33:10   File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
2022-07-25 06:33:10     return _MultiProcessingDataLoaderIter(self)
2022-07-25 06:33:10   File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 918, in __init__
2022-07-25 06:33:10     w.start()
2022-07-25 06:33:10   File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 112, in start
2022-07-25 06:33:10     self._popen = self._Popen(self)
2022-07-25 06:33:10   File "/opt/conda/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
2022-07-25 06:33:10     return _default_context.get_context().Process._Popen(process_obj)
2022-07-25 06:33:10   File "/opt/conda/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
2022-07-25 06:33:10     return Popen(process_obj)
2022-07-25 06:33:10   File "/opt/conda/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
2022-07-25 06:33:10     super().__init__(process_obj)
2022-07-25 06:33:10   File "/opt/conda/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
2022-07-25 06:33:10     self._launch(process_obj)
2022-07-25 06:33:10   File "/opt/conda/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
2022-07-25 06:33:10     reduction.dump(process_obj, fp)
2022-07-25 06:33:10   File "/opt/conda/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
2022-07-25 06:33:10     ForkingPickler(file, protocol).dump(obj)
2022-07-25 06:33:10 OverflowError: cannot serialize a bytes object larger than 4 GiB
```

I follow your scripts that build datastore and build knntargets. Here are my scripts to train knn mt model :
```bash
python train.py \
    ${DATA_PATH} \
    --task translation_with_stored_knnls \
    --knn-k ${K} --save-k 64 --train-knntarget-size ${TrainKNNTarget_SIZE} --valid-knntarget-size ${ValidKNNTarget_SIZE} \
    --knntarget-filename $KNNTarget_PATH --knndistance-fp16 \
    --arch transformer_wmt19_de_en_with_datastore --share-all-embeddings \
    --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
    --lr 0.0005 --lr-scheduler inverse_sqrt --min-lr 1e-09 \
    --warmup-updates 4000  --warmup-init-lr 1e-07  \
    --dropout 0.2 --weight-decay 0.0001 \
    --attention-dropout 0.1 --activation-dropout 0.1 \
    --criterion knn_label_smoothed_cross_entropy --label-smoothing 0.1 --knn-temp ${TEM} --distil-strategy ${Strategy} --kl-loss-combine-rate 0.5 \
    --max-tokens 1280 \
    --update-freq 1 \
    --seed 910 \
    --eval-bleu \
    --eval-bleu-args '{"beam": 5, "max_len_a": 1.2, "max_len_b": 10}' \
    --eval-bleu-detok moses \
    --eval-bleu-remove-bpe \
    --eval-bleu-print-samples \
    --best-checkpoint-metric bleu --maximize-best-checkpoint-metric \
    --keep-last-epochs 10 \
    --max-epoch 50 \
    --save-dir $MODEL_PATH \
    --fp16 > $TEST_RES_DIR/knn${K}''_temp${TEM}''_time_itp64.txt 
```

Could you please help me to solve this error? Thanks a lot and looking forward to your reply.

**Comment by FadedCosine** [comment]
I am sorry, but I have no idea about this error 😢
