### ISSUE TITLE
ValueError: mmap length is greater than file size

### ISSUE THREAD

**Issue by robotsp** [FadedCosine/kNN-KD#5]
When I build faiss through keys.npy and val.npy files, there is an error called "ValueError: mmap length is greater than file size".

02/14/2023 02:53:04 - INFO - __main__ -   load dstore fp16 4259960, 1024
Traceback (most recent call last):
  File "../train_datastore_gpu.py", line 69, in <module>
    shape=(args.dstore_size, args.dimension))
  File "/usr/local/lib/python3.6/site-packages/numpy/core/memmap.py", line 264, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
ValueError: mmap length is greater than file size

What's the problem and how I can solve it?

@FadedCosine

**Comment by robotsp** [comment]
The problem is solved by altering the mode="r" to mode="r+" in train_datastore_gpu.py.
